### ISSUE TITLE
Volume adjustment roller changes keyboard lightning back to default(factory) RGB

### ISSUE THREAD

**Issue by fulvouscoder** [mortendynamite/g19daemon#10]
After I setup my RGB using the LCD Keys (R=60,G=255,B=200), I press OK key and the configuration is saved to the Dynamite folder:
`
/home/username/.config/Dynamite/G19Daemon.conf
`
As soon as I use the Volume adjustment roller to change the sound volume, I notice that the keyboard lighting reacts to the change, going on a scale and when the sound is muted all the keyboard glows red. This is a very cool effect smile !!!

Now here lies the problem, after using the roller (or the Mute key), the keyboard lighting reacts accordingly, however it returns to a default state, which is not what I configured (the default seems to be a purpleish color).
It seems to me that the configuration file saved under Dynamite is only being loaded when the user saves changes with the LCD keys.

**Comment by jimmyd-be** [comment]
Is this bug not already fixed with the code change of #9?

**Comment by fulvouscoder** [comment]
Yes sir! we can close this one
