### ISSUE TITLE
Suggestions - G keys and M keys functionality

### ISSUE THREAD

**Issue by fulvouscoder** [mortendynamite/g19daemon#11]
Hello,

at the moment, the MR key does not have any functionality, the G keys are limited to opening applications and M keys profiles only store the G keys settings.

a) Would it be possible to allow the MR key to be programmable, just like the G keys, in the GUI?

b) Is it possible to assign keystrokes to the G keys, for example:

- G3 = Key Press 'Shift' + Key Press 'K' + Key Release 'K' + Key Press 'O' + Key Release 'O' + Key Release 'Shift'
- Pressing G3 executes the Hold Shift and types KO

c) While using the M1,M2,M3 keys the user has effectively 36 G keys at his disposal.
c.1) to increase this number, a user could use a modifier key:

- while M1 active press G1 = open firefox
- while M1 active press Shift + G1 = open brave
- while M2 active press G1 = open chrome
- while M2 active press Shift + G1 = open calculator

c.2) to have direct access to functionalities saved on a different profile, without actually switch the entire profile:

M1 profile has the following settings;
- press G1 key = open clock

M2 profile has the following settings;
- press G1 key = open calculator

If the user presses a modifier key, e.g. CTRL:
- while M1 active press CTRL + G1 = open calculator

c.3) to bind key lightning settings to each profile:

M1 profile has the following settings;
- key lightning set to R=255,G=0,B=0
M2 profile has the following settings;
- key lightning set to R=55,G=65,B=149

Thanks

**Comment by jimmyd-be** [comment]
The key colors for every profile is possible and a great added value.

Adding keystrokes is also possible but it will be limited to one key combinatie for a g key. For example cntrl + shift + K.

Mr key can also be programable like the g Keys. Gui need to be change for this. Adding this is a few minutes work.

Combining gkeys with other Keys like shift or cntrl isnt posible to the way the deamon works. When I was programming the g key functionality I tried to use the g Keys to send a keystroke to the Linux kernel but x11 does not supporting custom Keys and I need to bind the gkeys to already existing Keys like Phone Keys or Something like that.

**Comment by jimmyd-be** [comment]
I placed all the suggestions to the [project page](https://github.com/mortendynamite/g19daemon/projects/1)
Also I added some of my own (like game switch support).

**Comment by jimmyd-be** [comment]
For the MR-key. I will make it like a profile. So you have 4 profiles with 12 keys = 46 combos.

**Comment by fulvouscoder** [comment]
Great work!
Just to let you know I am downloading and will provide an update on the tests asap.

**Comment by jimmyd-be** [comment]
@fulvouscoder if you also have suggestions for new plugins. Please shoot.
