### ISSUE TITLE
Unable to restart after application crash

### ISSUE THREAD

**Issue by Neo-Desktop** [mortendynamite/g19daemon#17]
If for whatever reason g19daemon crashes, it leaves behind a PID file in the run directory.

This means it's not possible to relaunch the application without first removing the PID file.

I would propose a change to the startup logic in `main.cpp` to compensate for this, (i.e. if the file exists and is actively running then exit early, otherwise just remove the PID file and continue startup)

Let me know if you'd prefer this in a pull request

**Comment by jimmyd-be** [comment]
I will look into it. I have already a sollution in mind that does not need to have the pid file in line. I will develop it asap (begin of the week).

**Comment by Neo-Desktop** [comment]
Sounds good :) thanks for the prompt response!

**Comment by jimmyd-be** [comment]
The latest code change has the change for checking a running instance without pid file.
Enjoy it.
