### ISSUE TITLE
Daemon is not loading color

### ISSUE THREAD

**Issue by Neshura87** [mortendynamite/g19daemon#19]
Daemon not loading colors on start.
Every other setting is successfully loaded by the daemon. G-Key commands as well as the default Plugin get loaded but the key color is set to white, pressing the associated M-key however then loads the color.

**Comment by jimmyd-be** [comment]
I changed the code so that when G19Daemon is loading it will initialize the M1 backgroundcolors to the keyboard.
Currently you need to manually build it. The bilds for deb or rpm files is still running.
