### ISSUE TITLE
Installed latest release using .deb nothing is happening when opening

### ISSUE THREAD

**Issue by ThomasCanCode** [mortendynamite/g19daemon#21]
Hello, I have installed it on Linux Mint, after installing with package manager, I try to open the app g19daemon but nothing is happening, nothing is the system tray or on the keyboard, any suggestions?

Thank you & great work, I really hope I can get it to work on my PC!

**Comment by jimmyd-be** [comment]
What error are you getting when you run 'g19deamon' in de command line?

**Comment by ThomasCanCode** [comment]
g19deamon: command not found

**Comment by jimmyd-be** [comment]
Sorry my bad. I have typed a typo in the command. Please try it with 'g19daemon'?

**Comment by ThomasCanCode** [comment]
haha no problem, new error:
g19daemon: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not
found (required by g19daemon)

I think I understand the issue now, but still I don't know how to install
the missing dependancy, I am still new to linux, today is my first day of
ditching windows XD
Could you please help with the proper command to install this?

**Comment by jimmyd-be** [comment]
It looks like you better install it by manually building it. If you have any troubles trying that I will try to fix the deb file. But I can probably do that in a couple of days.

**Comment by jimmyd-be** [comment]
Cmake can be installed with (in command line)
sudo apt-get install cmake

And for Qt you can try this
sudo apt install qt5-default qttools5-dev-tools qttools5-dev

**Comment by ThomasCanCode** [comment]
Thanks, I downloaded all required packages, cloned your repo, cd to the g19daemon folder and ran the git submodule, but got the following error in the terminal:

`git submodule update --init --recursive
Submodule 'src/singleapplication' (git@github.com:itay-grudev/SingleApplication.git) registered for path 'src/singleapplication'
Cloning into '/home/toma/g19daemon/src/singleapplication'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:itay-grudev/SingleApplication.git' into submodule path '/home/toma/g19daemon/src/singleapplication' failed
Failed to clone 'src/singleapplication'. Retry scheduled
Cloning into '/home/toma/g19daemon/src/singleapplication'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:itay-grudev/SingleApplication.git' into submodule path '/home/toma/g19daemon/src/singleapplication' failed
Failed to clone 'src/singleapplication' a second time, aborting
`

**Comment by ThomasCanCode** [comment]
Okay, I got it to build, I manually went to g19daemon repo, src, singleapplication, downloaded zip and extracted to where I cloned the repo.

Got it to build, its showing:

`[100%] Linking CXX shared library libhardwaremonitor.so
[100%] Built target hardwaremonitor
make: *** No rule to make target 'install'.  Stop.`

**Comment by ThomasCanCode** [comment]
Got it to build with sudo cmake --install build
Now I can run g19daemon in terminal and I receive
`qt5ct: using qt5ct plugin`

I have opened the GUI, however I cannot get the M1,M2,M3 buttons to work, the keyboard is just as before, unresponsive, what is the next step?

Thank you!

**Comment by jimmyd-be** [comment]
Hmm strange. Let me give some time to simulate your situation and try to fix it. Are you using Linux Mint 20.3 cinnamon edition?

**Comment by ThomasCanCode** [comment]
Thank you!
Yes 20.3 cinnamon

**Comment by jimmyd-be** [comment]
Ok I have quickly simulated your environment. I found probably the sollution of your problem.
When I build the code in Linux mint and run it I'm getting following logs:
`qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/007: Permission denied
libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
"Cannot open device" 

Load Settings
Loading settings
Loading General settings
"Total screens loaded from settings: 0 of 0"
Loading sub screen order
Loading main screen order
"Loaded screen orders: 0"
Load StartScreen
Plugin initialized
qt5ct: D-Bus system tray: yes
`

The problem here was that the user does not have the permission to access the keyboard device. You can give the current user permission by running 'sudo usermod -a -G input {username}'. When you run this command you should logout en login again. That should fix the permission denied issue. You can test this quickly by opening the UI and press the M2, M3 MR button, the UI will auto open the tab of the pressed key.

**Comment by ThomasCanCode** [comment]
Thank you!

It works now after updating the user permission, time to install the
hardware monitor plugin! :)

**Comment by jimmyd-be** [comment]
Have fun with it.
I will let this issue open to fix the Qt dependency in the deb file.

**Comment by jimmyd-be** [comment]
Because of different versions of Qt on different Linux system, I will look into replacement deb and rpm with appimage builds.

**Comment by jimmyd-be** [comment]
Newest deb file can be installed without any issues in LInux Mint 20 (and probably Ubuntu 21.10).
