### ISSUE TITLE
Hardware-Monitor-Applet

### ISSUE THREAD

**Issue by s90180007** [mortendynamite/g19daemon#30]
Thank you for fixing the build. Is it possible to access the Hardware-Monitor-Applet repository? The plugin requires to click on the link, but I get a 404 error. I spent so much time trying to find the right repository, but they were all deleted.

**Comment by s90180007** [comment]
> Do you mean this repo https://github.com/jimmyd-be/Hardware-Monitor-Applet ?

Thank you! Can I make a linear scale with numbers in the same color as the title?
![Graph screen](https://github.com/mortendynamite/g19daemon/assets/98289633/33802aea-192b-4ab3-834c-a4fa348a8c66)

**Comment by jimmyd-be** [comment]
You can configure the colors of the lines to every color you want.
Changing the color of the grid is not possible yet.
For making the scale linear you can configure minimum and maximum values. This will make the scale fixed
