### ISSUE TITLE
dependent package installations in ubuntu 22.04?

### ISSUE THREAD

**Issue by w4b-zero** [mortendynamite/g19daemon#32]
would it be possible to update the required packages for Ubuntu 22.04 as well as for qt6 in the readme.md?

**cmake 3.24.4
`
test -f /usr/share/doc/kitware-archive-keyring/copyright || wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
sudo apt-get update
sudo apt-get install cmake
`

**packages
`sudo apt install build-essential debhelper libusb-1.0-0-dev libpulse-dev cppcheck libxcb-cursor0 libxcb-cursor-dev libglx-dev libgl1-mesa-dev`

**qt6.7.3 - custom installation/full (online_installer.run) ~/Qt

`sh ./mb.sh`
*** -DCMAKE_PREFIX_PATH=/home/zero/Qt/6.7.3/gcc_64 added to the cmake command (without it it didn't find qt6)
*** make install changed to make because the error came up that there was no rule for install
```
cd build
sudo make install 
```
*** installation without error.

unfortunately the daemon doesn't start.
how do I have to prepare the system to be able to start the daemon?

*** with qt5 (g19daemon 0.5.3) it still worked under ubuntu 22.04

**Comment by jimmyd-be** [comment]
For install QT6 in Ubuntu you can try using https://github.com/miurahr/aqtinstall

I cannot test this out because I'm on fedora and QT6 is already installed there.

Let me know if this works, then I will add this to the readme.

**Comment by jimmyd-be** [comment]
I will close this thread because of no response back. Please reopen it if this did not work
