### ISSUE TITLE
libpavolume.so cannot be loaded

### ISSUE THREAD

**Issue by lonelobo0070** [mortendynamite/g19daemon#5]
Cannot load library /usr/lib/g19daemon/0.1/plugins/libpavolume.so: (/usr/lib/g19daemon/0.1/plugins/libpavolume.so: undefined symbol: pa_operation_unref).

When I start the G19daemon on Kubuntu 20.04 I'm getting the above error. I cannot find the issue because the method is in the Pulseaudio API. Do you know why this occurs?

**Comment by mortendynamite** [comment]
No, I don’t know why I use Gentoo so I don’t know much about Kubuntu.
Have you tried to do a clean build can be an update lib.

**Comment by lonelobo0070** [comment]
I tried a clean build also checked the lib version and checked the documentation about the lib. The method is still available in this release. So at the moment I haven't any clue to fix this. Maybe StackOverFlow will help me with this. I let you know if I found the issue of this.

**Comment by lonelobo0070** [comment]
I found the issue. IN the CMakeLists.txt file of the pavolume plugin the pulseaudio library is not in the target link libraries. This fixed the issue.

**Comment by mortendynamite** [comment]
Nice find. Wonder why I did not get that error.

**Comment by lonelobo0070** [comment]
The fix did give another issue. Now when I rease or increase the volume the pavolume plugin is shown. After x seconds the active plugin is again shown. Then after x seconds the screen is flashing between the active plugin and the preactive plugin. After I fix this I will merge again to your branch.
